/* Generated by Babel */
'use strict';

(function () {

    var $ = document.querySelector.bind(document);
    var $$ = document.querySelectorAll.bind(document);

    var navElements = Array.from($$('.nav'));

    console.log(navElements);

    navElements.forEach(function (element) {
        element.addEventListener('click', function () {
            var temp = element.nextElementSibling;
            console.warn(temp);
            element.nextElementSibling.classList.toggle('hidden');
        });
    });
})();