/* Generated by Babel */
"use strict";

(function () {

    var FORM_VISIBLE_HEIGHT = "auto";
    var mail = undefined,
        name = undefined,
        surname = undefined,
        gender = undefined;
    var checkMail = undefined,
        checkName = undefined,
        checkSurname = undefined;
    var initEventListener = function initEventListener() {
        document.querySelector("#mailInput").addEventListener('focus', handleFormFocus);
        document.querySelector('#mailInput').addEventListener('keyup', checkFormData);
        document.querySelector('#surnameInput').addEventListener('keyup', checkFormData);
        document.querySelector('#nameInput').addEventListener('keyup', checkFormData);
    };

    var handleFormFocus = function handleFormFocus() {
        setFormHeight(FORM_VISIBLE_HEIGHT);
        setInitialFormState();
        document.querySelector("#mailInput").removeEventListener("focus", handleFormFocus);
    };

    var setFormHeight = function setFormHeight(newHeight) {
        var currentHeight = document.querySelector("#formular").style.height;

        if (setFormHeight !== newHeight) {
            document.querySelector("#formular").style.height = newHeight;
        }
    };

    var setInitialFormState = function setInitialFormState() {
        toggleInputErrorState(false, "#mailInput");
        toggleInputErrorState(false, "#nameInput");
        toggleInputErrorState(false, "#surnameInput");

        deactiveButton(true);
    };

    var toggleInputErrorState = function toggleInputErrorState(state, id) {
        if (state) {
            document.querySelector(id).classList.remove("error");
        } else {
            document.querySelector(id).classList.add("error");
        }
    };

    var deactiveButton = function deactiveButton(state) {
        document.querySelector("#senden").disabled = state;
        console.log("In the button function");
    };

    var checkFormData = function checkFormData(event) {
        var id = '#' + event.target.id;

        //^ Add definiert den Anfang des Textes
        //$ Dollar markiert das Ende des Textes
        //+ bedeutet 1 oder beliebig viele.
        //NICHT IN ANFÜHRUNGSSTRICHEN SCHREIBEN
        var mailPattern = /^[0-9a-zA-Z._-]+@[0-9a-zA-z._-]+[.][a-zA-Z]{2,8}$/;

        //i steht für case insensitive
        var namePattern = /^[a-zäüöß -]+/i;
        console.log('checkFormData');

        switch (id) {
            case "#mailInput":
                mail = document.querySelector(id).value;
                checkMail = mailPattern.test(mail);
                toggleInputErrorState(checkMail, id);
                break;
            case "#nameInput":
                name = document.querySelector(id).value;
                checkName = namePattern.test(name);
                toggleInputErrorState(checkName, id);
                break;
            case "#surnameInput":
                surname = document.querySelector(id).value;
                checkSurname = namePattern.test(surname);
                toggleInputErrorState(checkSurname, id);
                break;
        }

        if (checkMail && checkName && checkSurname) {
            deactiveButton(false);
        } else {
            deactiveButton(true);
        }

        console.log(checkMail);
    };

    initEventListener();
})();