/* Generated by Babel */

/*------------------------------------------------------------------------------------------
| Class Definition
--------------------------------------------------------------------------------------------*/

"use strict";

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var Fighter = function Fighter(x) {
    var _this = this;

    _classCallCheck(this, Fighter);

    this.name = x;
    this.str = Math.floor(Math.random() * (30 - 10 + 1)) + 10;
    this.dex = Math.floor(Math.random() * (30 - 10 + 1)) + 10;
    this.hp = 100;
    this.dmg = "Pacifist";

    //If you define a variable with a let the Variable is declared private.
    var hf = 12;
    this.hit = function (opponent) {
        var dmg = Math.floor(Math.random() * (_this.str - _this.str / 4 + 1) + _this.str / 4);

        var evadeChance = opponent.dex * (Math.random() * 8);
        if (evadeChance <= 50) {
            opponent.hp -= dmg;
            console.log("HIT!: " + dmg);
            console.log("HP!: " + opponent.hp);
        } else {
            console.log("MISS!");
            console.log(hf);
        }
    };

    this.updateList = function () {
        var list = document.querySelector('#player ul');
        list.children[0].children[0].innerHTML = _this.name;
        list.children[1].children[0].innerHTML = _this.str;
        list.children[2].children[0].innerHTML = _this.dex;
        list.children[3].children[0].innerHTML = _this.hp;
    };
};

;

var Ring = function Ring() {
    var _this2 = this;

    _classCallCheck(this, Ring);

    //Vars
    this.battleMessages = [];
    var firstHitter = undefined;
    var secondHitter = undefined;

    //Methodes
    this.battle = function (player1, player2) {

        if (Math.random() * 2 <= 1) {
            _this2.firstHitter = player1;
            _this2.secondHitter = player2;
            _this2.battleMessages.push(player1.name + " Attacks First!");
            console.log(player1.name + " Attacks First!");
        } else {
            _this2.firstHitter = player2;
            _this2.secondHitter = player1;
            console.log(player2.name + " Attacks First!");
        }

        while (player1.hp >= 0 && player2.hp >= 0) {
            _this2.firstHitter.hit(_this2.secondHitter);

            if (Math.random() * 6 <= 3) {
                _this2.firstHitter.hit(_this2.secondHitter);
                console.log(_this2.firstHitter.name + "lands a nice blow!");
            } else {
                _this2.secondHitter.hit(_this2.firstHitter);
                console.log(_this2.secondHitter.name + "lands a nice blow!");
            }
        }
    };
}

/*------------------------------------------------------------------------------------------
| Variables
--------------------------------------------------------------------------------------------*/

;

var player1 = null;

/*------------------------------------------------------------------------------------------
| Eventhandler
--------------------------------------------------------------------------------------------*/

//document.getElementById('#create-fighter').addEventListener('click', () => {
//    player1 = new Fighter(document.querySelector('#player ul'));
//    player1.updateList();
//});

document.querySelector('#create-fighter').addEventListener('click', function () {
    player1 = new Fighter(document.querySelector('#fighterName').value);
    console.log(player1.name);
    console.log(player1.hit(new Fighter('hitter')));
    player1.updateList();
});

document.querySelector('#fight').addEventListener('click', function () {
    var arena = new Ring();

    if (typeof player1 == null) {
        console.log("Create a player first:");
    } else {
        arena.battle(player1, new Fighter('dummy'));
    }
});

/*------------------------------------------------------------------------------------------
| Main
--------------------------------------------------------------------------------------------*/