/* Generated by Babel */
'use strict';

(function () {

    var $ = document.querySelector.bind(document);
    var $$ = document.querySelectorAll.bind(document);

    var allPix = Array.from($$('.pic-row img'));
    var bigPic = $('#hero-img');

    var initListener = function initListener() {

        bigPic.setAttribute('data-index', 0);
        //Eventlistener for Thumbnails
        allPix.forEach(function (element, index) {
            element.setAttribute('data-index', index);
            element.addEventListener('click', function () {
                changeImg(index);
            });
        });

        //Eventlistener for Arrow keys

        var arrows = Array.from($$('.btn-control'));

        arrows[0].addEventListener('click', function () {

            var currentIndex = parseInt(bigPic.getAttribute('data-index'));

            currentIndex = currentIndex == 0 ? allPix.length - 1 : currentIndex -= 1;

            changeImg(currentIndex);
        });

        arrows[1].addEventListener('click', function () {

            var currentIndex = parseInt(bigPic.getAttribute('data-index'));

            currentIndex = currentIndex == allPix.length - 1 ? 0 : currentIndex += 1;

            changeImg(currentIndex);
        });

        $('#hero-input').addEventListener('keyup', function () {
            var index = parseInt($('#hero-input').value);
            if (index >= allPix.length) {
                $('#hero-input').classList.add('error');
            } else {
                changeImg(index - 1);
            }
        });
    };

    var changeImg = function changeImg(index) {
        var path = allPix[index].getAttribute('src');
        bigPic.setAttribute('src', path);
        bigPic.setAttribute('data-index', index);
        $('#hero-input').setAttribute('placeholder', index + 1);
    };

    initListener();
})();