/* Generated by Babel */


//Die while Schleife

//var status = true;
//
//while(status){
//    console.log("Super!");
//    status = confirm("Nochmal?(While Schleife)");
//    alert("Wert Status: " + status);
//}

//Die do While Schleife

//do{
//   
//    console.log("Super!");
//   
//}while(confirm("nochmal? (Do While Schleife)"));

//Selbst aufrufende funktion
"use strict";

(function () {})();

//Elemente aus dem Aktuellen Dokument auswählen

var dasErstePImHTML = document.querySelector('p');
console.log("Dies ist das erste P Objekt des HTML Dokuments: " + dasErstePImHTML);

//Inhalt des ersten P Tags des documents einsehen.
var inhaltDesErstenPImHTML = document.querySelector('p').innerHTML;
console.log("Dies ist der Inhalt des ersten P tags des HTMLs: " +inhaltDesErstenPImHTML);

//Inhalt des ersten P tags neu setzen.
inhaltDesErstenPImHTML = document.querySelector('p').innerHTML = "Tchöööö";

//Usernamen einlesen und dann auf der Seite ausgeben
var username = prompt("Ihr Name:");
document.querySelector('h3').innerHTML ='<span style="background:red;">Hallo</span>' + username;

//Username in den HTML String mit einlesen
var username = prompt("Ihr Name:");
document.querySelector('h4').innerHTML =`<span style="background:red;">Hallo, ${username}</span>` + username; 

//Alternative Schreibweise
document.querySelector('h5').innerHTML = '<span style="background:red;">Hallo, ' + username + '<span>';

//Mit dem Queryselector ein HTMLElement über eine Klasse auswählen.
document.querySelector('.nacht').innerHTML = '<span style="background:blue;">Hallo, ' + username + '<span>';

//Mit dem Queryselector ein HTMLElement über eine ID auswählen
document.querySelector('#tag').innerHTML = '<span style="background:green;">Hallo, ' + username + '<span>';

//Mit Javascript CSS verändern. Die geänderten Eigenschaften werden als inline-style an die HTML Datei angehängt.
document.querySelector('.css').style.color = "red";  





