/* Generated by Babel */
'use strict';

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError('Cannot call a class as a function'); } }

(function () {

    var $ = document.querySelector.bind(document);

    var Todo = function Todo(text) {
        _classCallCheck(this, Todo);

        this.text = text;
        this.date = new Date();
        this.isChecked = false;
    }

    //  get date(){
    //    return this.date;
    //  }
    //
    //  get isChecked(){
    //      return this.isChecked;
    //  }
    //   
    //  set isChecked(newValue){
    //      return this.isChecked = newValue;
    //  }
    ;

    var todoList = [];

    $('#submitBtn').addEventListener('click', function () {
        var input = $('#todoInput').value;
        todoList.push(new Todo(input));
        console.log(todoList);
        updateTable();
    });
    var updateTable = function updateTable() {
        todoList.forEach(function (element, index) {
            $('#mrTBody').innerHTML += '<tr><td>' + (index + 1) + '</td><td>' + element.text + '</td><td>' + element.date + '</td><td><button type="button" class=\'btn btn-success\'><span class="glyphicon glyphicon-ok"></span></button>\n                             <button type="button" class=\'btn btn-danger\'><span class="glyphicon glyphicon-trash"></span></button></td></tr>';
        });
    };
})();