/* Generated by Babel */
"use strict";

var umrechner = function() {
 do{
 
    var result = ''; 
     
    var value = prompt("Geben sie den Betrag ein: ");
    
    if(value.indexOf('$') !== -1){
        
        result = ((value * 0.904) + " €").toString();
        
     }else if(value.indexOf('€') !== -1){
        
         result = ((value *  1.1345)  + " $").toString();
         
     }
     else{
         result = "Keine valide Eingabe!";
     }
    
    alert ("Das Ergebnis lautet: " + result);

 }while(comfirm("Neuen Wert berechnen?"));
    
}

umrechner();



//Umrechner Michi Version
var umrech2 = function(){
    let input = parseInt(prompt("Betrag: "));
    let euro = input * 0.904;
    
    console.log("input + '$ ->' + euro + '€'");
}

//Umrechner Michi short Version

var umrech3 = function(){
    console.log(parseInt(prompt("Betrag")) * 0.904 + '€');
}


//Einführung Arrays
let busString ="Hans, Peter, Silie, Otto, Anna";

let bus = ["Hans", "Peter","Silie", "Otto", "Anna"];

//Array Definition alternative Schreibweise
let bus2 = new Array("Hans", "Peter","Silie", "Otto", "Anna");

//length gibt die Menge der im Array enthaltenen Elemente aus.
console.log(bus.length);

//Zugriff auf einen Index/Element eines Arrays.
console.log(bus[1]);

//Sotieren mit der .sort() methode
let matheBus = [1,2,3,4,55,56,7,8,12];

//Sortieren mit eigener Function (a - b) klein bis Groß (b - a) von Groß nach klein.
console.log(matheBus.sort());
console.log(matheBus((a, b) =>{
    return a - b;
}));

//Shorthand
console.log(matheBus((a, b) => return a - b;));

//Element am Schluss anhängen
console.log(matheBus.push("Hans"));

//Pop das letzte Element aus dem Array nehmen
console.log(matheBus.pop());

//Elemente an den Anfang eines Arrays hinzufügen.
console.log(matheBus.unshift('Mama'));

//Das erste Element aus einem Array nehmen.
console.log(matheBus.shift());

//Teile des Arrays kopieren(kopiere von 2ter bis 5ter Stelle).
console.log(matheBus.slice(2,5));

//Teile des Arrays kopieren(kopiere ab der 2ten Stelle Fünf Elemente).
console.log(matheBus.slice(2,5));

//Teile des Arrays herausschneiden (destruktives Arbeiten).
console.log(matheBus.splice(2,5));

//Teile des Arrays herausschneiden und durch anderen Wert ersetzen.(bsp springe an die zweite Stelle, schneide 3 Elemente raus und ersetze es durch gustav)
console.log(matheBus.splice(2,3, 'Gustav'));

//Array Reihenfolge Umkehren
console.log(matheBus.reverse());

//Index von einem Element bestimmen
console.log(a.indexOf(1));

//Zwei Arrays zusammenkleben
var a = [1,2,3,4,5];
var b = [6,7,8,9];

console.log(a.concat(b));

//Alle Elemente eines Arrays überschreiben
console.log(a.fill("test"));

//String in Array umwandeln
console.log("Hans, Peter, Manni, Dave, jannis".split(','));

//Leerzeichen am Anfang und Ende aus einem String entfernen.
console.log(" Bernd ".trim());

//Array in einen String umwandeln
var c = ["Mama", "Papa", "Ralf" , "Laura"];
c.join(" ");

