/* Generated by Babel */
'use strict';

(function () {

    var $ = document.querySelector.bind(document);
    var $$ = document.querySelectorAll.bind(document);

    var playerHand = [];

    var deck = [];

    var bankHand = [];

    var startGame = function startGame() {

        playerHand = [];
        bankHand = [];
        $('#winner').classList.remove('show');

        deck = [['2c.png', 2], ['2d.png', 2], ['2h.png', 2], ['2s.png', 2], ['3c.png', 3], ['3d.png', 3], ['3h.png', 3], ['3s.png', 3], ['4c.png', 4], ['4d.png', 4], ['4h.png', 4], ['4s.png', 4], ['5c.png', 5], ['5d.png', 5], ['5h.png', 5], ['5s.png', 5], ['6c.png', 6], ['6d.png', 6], ['6h.png', 6], ['6s.png', 6], ['7c.png', 7], ['7d.png', 7], ['7h.png', 7], ['7s.png', 7], ['8c.png', 8], ['8d.png', 8], ['8h.png', 8], ['8s.png', 8], ['9c.png', 9], ['9d.png', 9], ['9h.png', 9], ['9s.png', 9], ['10c.png', 10], ['10d.png', 10], ['10h.png', 10], ['10s.png', 10], ['jc.png', 10], ['jd.png', 10], ['jh.png', 10], ['js.png', 10], ['qc.png', 10], ['qd.png', 10], ['qh.png', 10], ['qs.png', 10], ['kc.png', 10], ['kd.png', 10], ['kh.png', 10], ['ks.png', 10], ['ac.png', 11], ['ad.png', 11], ['ah.png', 11], ['as.png', 11]];

        $('#start-btn').disabled = true;
        $('#next-btn').disabled = false;
        $('#stop-btn').disabled = false;

        giveCard(playerHand);
        giveCard(playerHand);

        giveCard(bankHand);
        giveCard(bankHand);

        console.log(playerHand);
    };

    var stopGame = function stopGame() {
        $('#start-btn').disabled = false;
        $('#next-btn').disabled = true;
        $('#stop-btn').disabled = true;

        if (calcSum(playerHand) < 21) {
            while (calcSum(bankHand) < 17) {
                giveCard(bankHand);
            }
        }

        checkWinner();
    };

    var giveCard = function giveCard(hand) {
        var rand = Math.floor(Math.random() * deck.length);
        hand.push(deck[rand]);
        deck.splice(rand, 1);

        showCards(hand);
    };

    var showCards = function showCards(hand) {

        var field = undefined;
        if (hand == playerHand) {
            field = '#playerTable';
        } else {
            field = '#bankTable';
        }

        $(field + ' div').innerHTML = '';

        hand.forEach(function (element) {
            $(field + ' div').innerHTML += '<img src="img/' + element[0] + '" alt="' + element[1] + '"/>';
        });

        $(field + ' h2 span').innerHTML = calcSum(hand);
    };

    var calcSum = function calcSum(hand) {
        var result = 0;

        hand.forEach(function (element) {
            if (result + element[1] > 21 && element[1] == 11) {
                if (hand.length == 2 && hand[0][1] == 11) {
                    result = 21;
                    return result;
                }
                result += 1;
            } else {
                result += element[1];
            }
        });

        return result;
    };

    var checkWinner = function checkWinner() {

        var win = $('#winner h1');
        var playerSum = calcSum(playerHand);
        var bankSum = calcSum(bankHand);

        if (playerSum > 21 && bankSum < 22) {
            win.innerHTML = "Die Bank gewinnt!";
        } else if (bankSum > 21 && playerSum < 22) {
            win.innerHTML = "Der Spieler gewinnt!";
        } else if (playerSum < 22 && playerSum === bankSum) {
            win.innerHTML = "Die Bank gewinnt!";
        } else if (playerSum > 21 && bankSum > 21) {
            win.innerHTML = "Niemand gewinnt!";
        } else if (playerSum < 22 && playerSum > bankSum) {
            win.innerHTML = "Der Spieler gewinnt!";
        } else if (bankSum < 22 && bankSum > playerSum) {
            win.innerHTML = "Die Bank gewinnt";
        } else {
            win.innerHTML = "FEHLER!!!!";
        }

        $('#winner').classList.add('show');
    };

    $('#start-btn').addEventListener('click', startGame);

    //Funktionsaufruf gekapselt durch Funktionsübergabe
    $('#next-btn').addEventListener('click', function () {
        giveCard(playerHand);
    });
    $('#stop-btn').addEventListener('click', stopGame);
})();