/* Generated by Babel */
'use strict';

(function () {

    var fruits = Array.from(document.querySelectorAll('.fruit'));

    var search = function search() {

        var input = new RegExp(document.querySelector('#suche').value, 'i');

        fruits.forEach(function (element) {
            if (input.test(element.innerText)) {
                element.classList.remove('hidden');
            } else {
                element.classList.add('hidden');
            }
        });
    };

    var imgs = Array.from(document.querySelectorAll('#slider img'));
    var pos = 0;

    var next = function next() {
        document.querySelector('#slider').style.left = pos * -960 + 'px';
        pos++;
    };

    var prev = function prev() {
        document.querySelector('#slider').style.left = pos * -960 + 'px';
        pos--;
    };

    var direction = next;
    var autoSlide = function autoSlide() {

        if (pos <= 0) {

            direction = next;
        } else if (pos >= imgs.length - 1) {
            direction = prev;
        }

        direction();
        setTimeout(autoSlide, 2000);
    };

    //Do something
    autoSlide();
    document.querySelector('#suche').addEventListener('keyup', search);
})();