/* Generated by Babel */
'use strict';

(function () {

    var fruits = Array.from(document.querySelectorAll('.fruit'));

    var search = function search() {

        var input = new RegExp(document.querySelector('#suche').value, 'i');

        fruits.forEach(function (element) {
            if (input.test(element.innerText)) {
                element.classList.remove('hidden');
            } else {
                element.classList.add('hidden');
            }
        });
    };

    var imgs = Array.from(document.querySelectorAll('#slider img'));
    var pos = 0;

    var next = function next() {
        document.querySelector('#slider').style.left = pos * -960 + 'px';
        pos++;
    };

    var prev = function prev() {
        document.querySelector('#slider').style.left = pos * -960 + 'px';
        pos--;
    };

    var direction = next;
    var autoSlide = function autoSlide() {

        if (pos <= 0) {

            direction = next;
        } else if (pos >= imgs.length - 1) {
            direction = prev;
        }

        direction();
        setTimeout(autoSlide, 2000);
    };

    //Do something this da shit
    autoSlide();

    document.querySelector('#suche').addEventListener('keyup', search);

    var hoverImg = document.querySelector('.hoverImg');

    fruits.forEach(function (element) {
        element.children[0].addEventListener('mousemove', function (event) {
            hoverImg.style.display = 'block';
            hoverImg.style.opacity = 1;
            hoverImg.src = element.children[0].getAttribute('href');
            hoverImg.style.top = event.pageY + 15 + 'px';
            hoverImg.style.left = event.pageX + 15 + 'px';
        });
        element.children[0].children[0].addEventListener('mouseout', function (event) {
            hoverImg.style.opacity = 0.0;
            setTimeout(function () {
                hoverImg.style.display = "none";
            }, 1000);
        });
    });

    //    fruits.forEach((element) => {
    //        element.children[0].addEventListener('click', (event) => {
    //            document.querySelector('#layerImg').children[0].src = element.children[0].getAttribute('src');
    //            document.querySelector('#boxlayer').classList.remove('hidden');
    //        });
    //    });
    //   
    //    document.querySelector('#layer-close').addEventListener('click', () => {
    //        document.querySelector('#boxlayer').classList.add('hidden');
    //    })
})();